repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.1
  hooks:
  # Run the linter.
  - id: ruff
    args: [--fix]
  # Run the formatter.
  - id: ruff-format

- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.1
  hooks:
  - id: autoflake
    args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables', '--ignore-init-module-imports']
