version: '3'
services:
  gpt-all-star:
    container_name: gpt-all-star
    volumes:
      - ~/workspace:/usr/src/app/workspace
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7681:7681'
