version: '3'
services:
  gpt-all-star:
    container_name: gpt-all-star
    volumes:
      - ./projects:/usr/src/app/projects
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7681:7681'
