[tool.poetry]
name = "your-dev-team"
version = "0.1.0"
description = ""
authors = ["Yuya Kakui <y.kakui@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
python-dotenv = "^1.0.0"
jinja2 = "^3.1.2"
langchain = "^0.1.0"
openai = "^1.6.1"
tiktoken = "^0.5.2"
rich = "^13.7.0"
prompt-toolkit = "^3.0.43"
termcolor = "^2.4.0"
gitpython = "^3.1.41"
requests = "^2.31.0"

[tool.poetry.scripts]
your-dev-team = 'your_dev_team.main:app'

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[project.scripts]
your-dev-team = 'your_dev_team.main:app'

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
